config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, :body, presence: true

    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :comments
    has_one_attached :cover_image
    attr_accessor :remove_cover_image
    after_save { cover_image.purge if remove_cover_image == '1' }

    scope :published, -> { where.not(published_at: nil) }
    scope :draft, -> { where(published_at: nil) }
    scope :recent, -> { where("articles.published_at > ?", 1.week.ago.to_date) }
    scope :where_title, -> (term) { where("articles.title LIKE ?", "%#{term}%") }

    def long_title 
        "#{title} - #{published_at}"
    end

    def published?
        published_at.present?
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :articles

    default_scope { order :name }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article

    validates :name, :email, :body, presence: true
    validate :article_should_be_published

    after_create :email_article_author

    def article_should_be_published
        errors.add(:article_id, 'is not published yet') if article && !article.published?
    end

    def email_article_author
        puts "We will notify #{article.user.email} in Chapter 12" if article.user
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord
    attr_accessor :password

    validates :email, uniqueness: true, length: { in: 5..50 }, format: { with: /\A[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}\z/i }
    validates :password, presence: true, confirmation: true, if: :password_required?, length: { in: 4..20 }
    
    has_one :profile
    has_many :articles, -> { order 'published_at DESC, title ASC' }, dependent: :nullify
    has_many :replies, through: :articles, source: :comments

    before_save :encrypt_new_password

    def self.authenticate(email, password)
        user = find_by email: email
        return user if user && user.authenticated?(password)
    end

    def authenticated?(password)
        self.hashed_password == encrypt(password)
    end

    protected

    def encrypt_new_password
        return if password.blank?
        self.hashed_password = encrypt(password)
    end

    def password_required?
        hashed_password.blank? || password.present?
    end

    def encrypt(string)
        Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        return unless session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def authenticate
        logged_in? || access_denied
    end

    def logged_in?
        current_user.present?
    end

    def access_denied
        redirect_to(login_path, notice: "Please log in to continue") and return false
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_article, only: %i[ show ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @article = current_user.articles.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :cover_image, :remove_cover_image, :location, :exerpt, :body, :published_at, category_ids: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :load_article, except: :destroy
    before_action :authenticate, only: :destroy

    def create
        @comment = @article.comments.new(comment_params)
        if @comment.save
            respond_to do |format| 
            format.html { redirect_to @article, notice: 'Thanks for your comment' }
            format.js
            end
        else
            respond_to do |format|
                format.html { redirect_to @article, alert: 'Unable to add comment' }
                format.js { render :fail_create }
            end
        end
    end

    def destroy
        @article = current_user.articles.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to @article, notice: 'Comment deleted' }
            format.js
        end
    end

    private

    def load_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:name, :email, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        if user = User.authenticate(params[:email], params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash.now[:alert] = "Invalid login/password combination"
            render :new
        end
    end

    def destroy
        reset_session
        redirect_to root_path, notice: "You successfully logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate, only: [:edit, :update]
    before_action :set_user, only: [:show, :edit, :uodate, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to articles_path, notice: 'User successfully added.'
        else
            render action: new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to articles_path, notice: 'Update user information successfully.'
        else
            render action: 'edit'
        end
    end

    private

    def set_user
        @user = current_user
    end

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="article">
<h3>
<%= link_to article.title, article %>
<%= if article.owned_by? current_user %>
<span class="actions">
  <%= link_to 'Edit', edit_article_path(article) %>
  <%= link_to 'Delete', article, confirm: 'Are you sure?', method: :delete %>
</span>
<% end %>
</h3>
<hr>
<% if article.cover_image.attached? %>
<%= image_tag article.cover_image.variant(resize_to_limit: local_assigns.fetch(:cover_image_options, [200, 200])) %>
<% end %> 
<hr>
<%= article.body %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
    <% if article.cover_image.attached? %>
    <p>
    <%= image_tag article.cover_image.variant(resize_to_limit: [50, 50]) %>
    <br>
    <%= form.label :remove_cover_image do %>
    <%= form.check_box :remove_cover_image %> Remove this image
    <% end %>
    </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
    <%= b.label { b.check_box + b.text } %>
  <% end %> 
 </div>

  <div class="field">
    <%= form.label :exerpt %>
    <%= form.text_field :exerpt %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit_or_cancel(form) %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<%= render partial: @article, locals: { cover_image_options: [500, 500] } %>

<h3>Comments</h3>

<div id="comments">
  <%= render @article.comments %> |
  
</div>

<%= render 'comments/new' %>

<%= link_to "new comment", new_article_comment_path(@article), remote: true, id: 'new_comment_link' %>

app/views/comments/_comment.html.erb
<div class="comment">
<h3>
    <%= comment.name %> <<%= comment.email %>> said:
    <%= if article.owned_by? current_user %>
    <span class="actions">
        <%= link_to 'Delete', article_comment_path(article_id: @article, id: comment), confirm: 'Are you sure?', method: :delete, remote: true %>
    </span>
    <% end %>
</h3>
<%= comment.body %>
</div>

app/views/comments/_new.html.erb
<%= form_with(model: @article.comments.new, url: article_comments_path(@article), local: true) do |form| %>
<div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
</div>
<div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
</div>
<div class="field">
    <%= form.label :body %><br>
    <%= form.text_area :body %>
</div>
<div class="actions">
    <%= form.submit 'Add' %>
</div>
<% end %>

app/views/comments/create.js.erb
document.querySelector("#comments").insertAdjacentHTML("beforeend", "<%= escape_javascript render @comment %>");

document.querySelector("#main form").reset();

app/views/comments/destroy.js.erb
var comments = document.querySelector("#comments");
comments.removeChild(document.querySelector("#comment-<%= @comment.id %>"));

app/views/comments/fail_create.js.erb
alert("<%= @comment.errors.full_messages.to_sentence.html_safe %>");

app/views/comments/new.js.erb
document.querySelector("#comments").insertAdjacentHTML("afterend", "<%= escape_javascript render partial: 'new' %>");

var comment_form = document.querySelector("#main form");
comment_form.style.opacity = 0;
setTimeout(function() {
    comment_form.style.transition = 'opacity 1s';
    comment_form.style.opacity = 1;
}, 10);

document.querySelector("#new_comment_link").style.display = 'none';

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAugAgain2024</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div id="header">
  <h1><%= link_to "Blog", root_path %></h1>
  <div id="user_bar">
  <% if logged_in? %>
  <%= link_to "New Article", new_article_path %> |
  <%= link_to "Edit Password", edit_user_path(current_user) %> |
  <%= link_to "Logout", logout_path %>
  <% else %>
  <%= link_to "Login", login_path %>
  <% end %>
  </div>
  </div>
  <div id="main">
  <%= content_tag :p, notice, class: 'notice' if notice.present? %>
  <%= content_tag :p, alert, class: 'alert' if alert.present? %>
  <%= yield %>
  </div>
  <div id="footer">
  A simple blog built for the book Beginning Rails 6
  </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions"> 
    <%= form.submit_or_cancel(form) %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', articles_path %>